### ISSUE TITLE
nil_only_functions has false positives

### ISSUE THREAD

**Issue by natefinch** [codelingo/codelingo#129]
So, I don't exactly understand the "code" for this tenet, but it incorrectly marks functions as only returning nil *all the time* in our code.  And these aren't edge cases, this is just normal go code.  I'm not sure what's tripping it up.

**Comment by waigani** [comment]
Ah, that Tenet needs fixing.  You can type `/ignore` as a reply in the review comment. You also import the Tenets you want individually. Below are all the Tenets from the codelingo/go bundle. Pop that in your codelingo.yaml file and just comment out the ones you don't want .

```
tenets:
  - import: codelingo/go/bool-param
  - import: codelingo/go/empty-slice
  - import: codelingo/go/global-var
  - import: codelingo/go/golint
  - import: codelingo/go/goto
  - import: codelingo/go/init
  - import: codelingo/go/marshalling
  # - import: codelingo/go/nil_only_functions
  - import: codelingo/go/println-format-strings
  - import: codelingo/go/reallocated_slice
  - import: codelingo/go/sprintf
  - import: codelingo/go/tested
  - import: codelingo/go/todo
  - import: codelingo/go/unconvert
```
